name: Android CI (Compose)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install SDKMAN
        run: |
          curl -s "https://get.sdkman.io" | bash
          echo "sdkman_auto_answer=true" >> $HOME/.sdkman/etc/config
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk version
          sdk install gradle 8.7
          echo "source $HOME/.sdkman/bin/sdkman-init.sh" >> $GITHUB_ENV
          echo "GRADLE_HOME=$HOME/.sdkman/candidates/gradle/current" >> $GITHUB_ENV
      - name: Show Gradle version
        shell: bash
        run: |
          source $HOME/.sdkman/bin/sdkman-init.sh
          gradle -v

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install required SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build Debug APK
        shell: bash
        run: |
          source $HOME/.sdkman/bin/sdkman-init.sh
          gradle assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
